version: '3.8'

services:
  server:
    image: emmadal/oblackserver:1.0
    build:
      context: .
    container_name: go-server
    networks:
      - server-side
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3.0
    restart: always
    build:
      context: .
    container_name: mydb
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_USER: 
      MYSQL_ROOT_PASSWORD: 
    networks:
      - server-side
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/mysql/lib

networks:
  server-side: {}
  
volumes:
  dbdata: {}


  